server:
  port: 8080
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/resident_room_db
    password: password
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---
spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/resident_room_db_qa
    password: password
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'

---
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/resident_room_db_prod
    password: password
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
