server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_db
    password: password
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update